### ISSUE TITLE
 Add health-check python file

### ISSUE THREAD

**Issue by iromli** [GluuFederation/docker-oxtrust#25]
Current health-check endpoint returns status of both oxTrust and db_connection . However if db_connection is offline it is possible that oxTrust will keep receiving traffic. We need to parse the endpoint `/identity/restv1/health-check` which may give a response as bellow and correctly send back the code for the liveliness and readiness probes.

```
{"status": "running", "db_status":"offline"}
```

Desired use:

```yaml
          livenessProbe:
            exec:
              command:
                - python3
                - /app/scripts/healthcheck.py
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - python3
                - /app/scripts/healthcheck.py
```
